name: CMake with OpenMPI, GTest and OpenBlas

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

env:
  BUILD_TYPE: Release
  MPI_PROCESSES: 4  # Adjust as needed for parallel execution

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (CMake, OpenMPI, OpenBLAS, GoogleTest)
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential \
            openmpi-bin libopenmpi-dev \
            libopenblas64-dev \
            libopenblas-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DBLA_SIZEOF_INTEGER=8

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run Tests with OpenMPI and GTest
      working-directory: ${{github.workspace}}/build
      run: |
        set -e  # Exit on first failure
        cd test
        mpiexec -np ${{env.MPI_PROCESSES}} ctest -C ${{env.BUILD_TYPE}}
