name: CMake with OpenMPI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

env:
  BUILD_TYPE: Release
  MPI_PROCESSES: 4  # Adjust the number of MPI processes as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (CMake, OpenMPI)
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential openmpi-bin libopenmpi-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Run Tests with OpenMPI
      working-directory: ${{github.workspace}}/build/test
      run: |
        set -e  # Exit on first failure
        mpiexec -np ${{env.MPI_PROCESSES}} ctest -C ${{env.BUILD_TYPE}}
