name: CMake Build with OpenMPI, OpenBLAS (Spack), and GTest

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Install dependencies via APT
    - name: Install OpenMPI and GTest
      run: |
        sudo apt update
        sudo apt install -y openmpi-bin libopenmpi-dev libgtest-dev cmake make gcc g++

    # Setup Spack
    - name: Install Spack
      run: |
        git clone --depth=1 https://github.com/spack/spack.git ~/spack
        echo 'source ~/spack/share/spack/setup-env.sh' >> ~/.bashrc
        source ~/spack/share/spack/setup-env.sh

    # Install OpenBLAS using Spack
    - name: Install OpenBLAS with Spack
      run: |
        source ~/spack/share/spack/setup-env.sh
        spack install openblas
        echo "OPENBLAS_ROOT=$(spack location -i openblas)" >> $GITHUB_ENV

    # Configure CMake with OpenBLAS
    - name: Configure CMake
      run: |
        source ~/spack/share/spack/setup-env.sh
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DOpenBLAS_DIR=$OPENBLAS_ROOT

    # Build the project
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # Run tests
    - name: Test
      working-directory: ${{github.workspace}}/build/test
      run: ctest -C ${{env.BUILD_TYPE}}
